name: "ReactAdmin Enterprise Edition Action"
description: "Setup your CI to install EE packages"
author: "Marmelab"
branding:
  icon: "file-plus"
  color: "blue"
env:
  RA_TOKEN:
    description: "ReactAdmin Enterprise Edition secret CI token"
    required: true
runs:
  using: "composite"
  steps:
    # create `.npmrc` file to be used by npm or Yarn v1
    - name: Create .npmrc if not exists
      run: |
        [[ -f $HOME/.npmrc ]] || touch $HOME/.npmrc
      shell: bash
    - name: Complete .npmrc
      run: |
        echo "@react-admin:registry https://registry.marmelab.com" >> $HOME/.npmrc
        echo "//registry.marmelab.com/:_authToken=${{ env.RA_TOKEN }}" >> $HOME/.npmrc
      shell: bash
