name: "ReactAdmin Enterprise Edition Action"
description: "Setup your CI to install EE packages"
author: "Marmelab"
branding:
  icon: "file-plus"
  color: "blue"
env:
  CI_TOKEN:
    description: "ReactAdmin Enterprise Edition secret CI token"
    required: true
runs:
  using: "composite"
  steps:
    # create `.npmrc` file to be used by npm or Yarn v1
    - name: Create .npmrc if not exists
      run: |
        [[ -f .npmrc ]] || touch .npmrc
      shell: bash
    - name: Complete .npmrc
      run: |
        echo "@react-admin:registry https://registry.marmelab.com" >> .npmrc
        echo "//registry.marmelab.com/:_authToken=${{ env.CI_TOKEN }}" >> .npmrc
      shell: bash
    - run: cat .npmrc # TODO: remove it
      shell: bash
  # create `.yarnrc.yml` file to be used by Yarn v2 or more
  # TODO: add Yarn v2+ file
